zebra: fix compilation failure related to switch-enum
The following error happens when compiling:
> zebra/zebra_srv6.c: In function ‘get_srv6_sid’:
> zebra/zebra_srv6.c:1746:9: error: enumeration value ‘SRV6_SID_ALLOC_MODE_UNSPEC’ not handled in switch [-Werror=switch-enum]
>  1746 |         switch (alloc_mode) {
>       |         ^~~~~~
> zebra/zebra_srv6.c:1746:9: error: enumeration value ‘SRV6_SID_ALLOC_MODE_MAX’ not handled in switch [-Werror=switch-enum]
> cc1: all warnings being treated as errors
> make[1]: *** [Makefile:10780: zebra/zebra_

Fix this by adding the missing enums.

Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>