lib: json, fix error related to printbuf_strappend() API
On some distribution, the following error happens:

> build	20-Sep-2024 11:44:18	  CC       bgpd/bgp_community_alias.o
> build	20-Sep-2024 11:44:18	bgpd/bgp_aspath.c:632:3: error: implicit declaration of function ‘printbuf_strappend’; did you mean ‘printbuf_memappend’? [-Werror=implicit-function-declaration]
> build	20-Sep-2024 11:44:18	   printbuf_strappend(pb, "{\"string\":\"Local\",\"segments\":[");
> build	20-Sep-2024 11:44:18	   ^~~~~~~~~~~~~~~~~~
> build	20-Sep-2024 11:44:18	   printbuf_memappend

Old versions of json-c do not expose the printbuf_strappend() define.
The define needs to be exported at frr level, in order to be used.

Signed-off-by: Philippe Guibert <philippe.guibert@6wind.com>