distribute: fix compilation
In the function no_distribute_list the distfn has the wrong number of
parameters and compilation fails:
[snip]/lib/distribute.c:
 In function 'no_distribute_list':
   [snip]/lib/distribute.c:329:3:
   warning: initialization from incompatible pointer type [enabled by
   default]
        prefix ? &distribute_list_prefix_unset : &distribute_list_unset;
   [snip]/lib/distribute.c:336:2:
   error: too few arguments to function 'distfn'
   int ret = distfn(ifname, type, argv[2 + prefix]->arg);
   make[4]: *** [lib/distribute.lo] Error 1

Fix the number of expected argument.

Fixes: 981f35bf3b7f ("lib: distribute-list ipv6 can be (un)configured")
PR=61260
Signed-off-by: Thibaut Collet <thibaut.collet@6wind.com>
Acked-by: Philippe Guibert <philippe.guibert@6wind.com>